name: random-walkers
channels:
  - conda-forge
  - defaults
dependencies:
  - joblib=0.16.0
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab=2.2.8
  - matplotlib=3.3.2
  - nbdime=2.0.0
  - nodejs=14.11.0
  - numba=0.51.2
  - numpy=1.19.1
  - pandas=1.1.2
  - pip=20.2.3
  - pre-commit=2.7.1
  - pybind11=2.4.3
  - pytest-cov=2.10.1
  - pytest=6.0.2
  - python=3.8.5
  - scipy=1.5.2
  - setuptools=49.6.0
  - statsmodels=0.12.0
  - tqdm=4.49.0
  - xtensor-python=0.24.1
  - xtensor=0.21.6
  - pip:
    - git+https://github.com/akuhnregnier/clean_ipynb.git@working#egg=clean_ipynb
    - git+https://github.com/akuhnregnier/jupyter-notebook-tools.git@master#egg=jupyter-notebook-tools
